spring:
  datasource:
    url: jdbc:h2:mem:mybank
    driver-class-name: org.h2.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none      # lub validate
  flyway:
    enabled: false
