spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mybank}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    baseline-on-migrate: false
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql

  logging:
    level:
      root: INFO
      org.springframework: DEBUG


